
#############################################################################################
#@author erik.flores 
#@fecha 13/NOVIEMBRE/2017

#############################################################################################
#RUTA-UBICACION DEL ARCHIVO DE CONFIGURACION DEL log4j2
LOG4J2.SUBDIRECTORY=/resources/log4j2.xml

#############################################################################################
#PARAMETROS ORACLE
DB.ORACLEDRIVER=oracle.jdbc.OracleDriver
DB.ORACLEURL=jdbc:oracle:thin
DB.ORACLESERVER=
DB.ORACLEPORT=
DB.ORACLEDATABASE=

#PARAMETROS SQLSERVER
DB.MSSQLDRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
DB.MSSQLURL=jdbc:sqlserver
DB.MSSQLSERVER=
DB.MSSQLPORT=
DB.MSSQLDATABASE=

#PARAMETROS MYSQL
DB.MYSQLDRIVER=com.mysql.jdbc.Driver
DB.MYSQLURL=jdbc:mysql://srv00pcr03.atm.local:3306/CAMERAS
DB.MYSQLSERVER=srv00pcr03.atm.local
DB.MYSQLPORT=3306
DB.MYSQLDATABASE=CAMERAS

#############################################################################################
#URL SOLO SE DECLARA LO INHERENTE AL RDBMS
DB.MYSQLUSER=monitor.eventos
DB.MYSQLPASSWD=4F76AC60B8471263F3A21EB5396C14665DDA83A036FECF71E8C35B88E5DCB861

DB.ORACLEUSER=
DB.ORACLEPASSWD=
#
DB.MSSQLSUSER=
DB.MSMSSQLPASSWD=

#############################################################################################
#SENTENCIA A EJECUTAR
SQL.Q1=
SQL.Q2=
SQL.Q3=
SQL.Q4=


#INTERVALO DE TIEMPO PARA VERIFICACION DE EVENTOS (COMING SOON)
SQL.INTERVALO=

#############################################################################################
#PASO POR PARAMETROS LAS FECHAS A PROCESAR. 
#CASO CONTRARIO SE ENVIAN EN BLANCO PARA QUE EL PROGRAMA CALCULE EL RANGO DE FECHAS
#QUE VA DESDE LA ULTIMA VEZ QUE SE REGISTR\u00d3 EN AXISATM.SCRTV_REVISIONES HASTA EL DIA ANTERIOR A LA FECHA ACTUAL
#FORMATO YYY-MM-DD por ejemplo 2019-06-01
PARAM.FECHA_REPORTE=

PARAM.FECHA_INICIO=
PARAM.FECHA_FIN=

#############################################################################################
#PARAMETROS NOTIFICACION POR CORREO
MAIL.SERVER=10.9.10.66
MAIL.FROM=notificaciones.plavit@atm.gob.ec
#MAIL.TO=luis.samaniego@atm.gob.ec;gabriel.galeas@atm.gob.ec;marcos.salazar@atm.gob.ec;christian.leon@atm.gob.ec;
MAIL.TO=erik.flores@atm.gob.ec;
#MAIL.CC=erik.flores@atm.gob.ec;alex.almeidac@atm.gob.ec;
MAIL.CC=
MAIL.BCC=
#MAIL.SUBJECT=Resumen de eventos PLAVIT
MAIL.SUBJECT=TEST Resumen de eventos PLAVIT
MAIL.BODY=TEST Resumen de eventos PLAVIT
MAIL.PASS=A6A793BFC6AEE450A57DF7BD4BB66BF19C49DC5FF59EC2DECE2E769DF886CE3F
MAIL.PORT=25

#############################################################################################
