#############################################################################################
#@author erik.flores 
#@fecha 13/NOVIEMBRE/2017
#############################################################################################
#RUTA-UBICACION DEL ARCHIVO DE CONFIGURACION DEL log4j2
LOG4J2.SUBDIRECTORY=/resources/log4j2.xml
#############################################################################################
#PARAMETROS MYSQL
DB.MYSQLDRIVER=com.mysql.jdbc.Driver
DB.MYSQLURL=jdbc:mysql://srv00pcr03.atm.local:3306/CAMERAS
DB.MYSQLSERVER=srv00pcr03.atm.local
DB.MYSQLPORT=3306
DB.MYSQLDATABASE=CAMERAS
#############################################################################################
#URL SOLO SE DECLARA LO INHERENTE AL RDBMS
DB.MYSQLUSER=ENC2:ckn/V6Onv+hkETkzXLdrUM2Au0YaJmX1++Ky729+Vxvyb9GkHy7/7L/NppxBogjr/velW30Yq4Ldglo=
DB.MYSQLPASSWD=ENC2:Lj3Wj0RAUoE14fxHFuontIHFhQXiDWMpYAkX9ct9Aivq6XiyOlwoMxCRjsluNp0zg3IgOTtKG/lVIhg=
#############################################################################################
#SENTENCIA A EJECUTAR
SQL.Q1=
SQL.Q2=
SQL.Q3=
SQL.Q4=
#INTERVALO DE TIEMPO PARA VERIFICACION DE EVENTOS (COMING SOON)
SQL.INTERVALO=
#############################################################################################
#PASO POR PARAMETROS LAS FECHAS A PROCESAR. 
#CASO CONTRARIO SE ENVIAN EN BLANCO PARA QUE EL PROGRAMA CALCULE EL RANGO DE FECHAS
#QUE VA DESDE LA ULTIMA VEZ QUE SE REGISTR\u00d3 EN AXISATM.SCRTV_REVISIONES HASTA EL DIA ANTERIOR A LA FECHA ACTUAL
#FORMATO YYY-MM-DD por ejemplo 2019-06-01
PARAM.FECHA_REPORTE=
PARAM.FECHA_INICIO=
PARAM.FECHA_FIN=
#############################################################################################
#PARAMETROS NOTIFICACION POR CORREO
MAIL.SERVER=act.atm.gob.ec
MAIL.PORT=587
MAIL.FROM=notificaciones.plavit@atm.gob.ec
MAIL.PASS=ENC2:JvetmKUWIIQ62DgT4USCmdmbjP2qKQLDLmZblL4Fc0lx/BnGFiy+G1HTmRM0x50zgEwTxyaw
#MAIL.TO=luis.samaniego@atm.gob.ec;jesus.cuenca@atm.gob.ec;luis.tircio@atm.gob.ec;
MAIL.TO=erik.flores@atm.gob.ec;
MAIL.CC=erik.flores@atm.gob.ec;
MAIL.BCC=
MAIL.SUBJECT=Resumen de eventos PLAVIT
MAIL.BODY=Resumen de eventos PLAVIT
#############################################################################################
